config/routes.rb
Rails.application.routes.draw do
   get 'project/:id' => 'project#show', as: :project
  get 'project/' => 'project#index', as: :portfolio_root
  get 'shop/' => 'shop#index', as: :shop_root
  
=begin
  get 'api/admin/project/edit/:id'=> 'project#edit'
  get 'api/admin/project/:action' => 'project#:action'

  post 'api/admin/project/update' => 'project#update'
  post 'api/admin/project/create' => 'project#create'
  get 'admin/edit/:id' => 'admin#edit'
=end


  get ':controller/:action'

  root 'project#index'










end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :project_items
	enum project_type: {Drawing: 0, Painting: 1, Vector: 2}

	validates :project_title, presence: true

	#this doesn't work in strong parameters
	accepts_nested_attributes_for :project_items

	def thumbnail_image
		project_items.where(is_thumb_image: true).first.image_url
	end

	def project_view_items
		project_items.where(is_thumb_image: false)
	end
end

app/models/project_item.rb
class ProjectItem < ActiveRecord::Base
	belongs_to :project

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :verifyAdmin

	def index
		@isAdmin = true;
		@project_groups = Project.order(:sort_order)
								 .group_by(&:project_type)
								 .map do |p_type, project|
									{p_type: p_type, projects: project}
								 end 
		render 'project/index'
	end

	def new

	end

	def edit
		@id = params[:id]
	end

	private 

	def verifyAdmin

	end
end

app/controllers/application_controller.rb
require 'debugger'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from StandardError do |exception|
	new_logger =Logger.new('log/exceptions.log')
	new_logger.info('THIS IS A NEW EXCEPTION')
	new_logger.info(exception.message)
	new_logger.info(exception.backtrace)

	raise exception
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
	before_action :authenticate_admin, only:[:edit,:create,:update,:delete,:new]
	before_action :find_project, only:[:edit,:show,:delete]

#admin resources

	def edit
	    @project_types = Project.project_types
		render_to_string(formats: 'json')
	end

	def new
		@project = Project.new

		render_to_string(formats: 'json')
	end

	def create
		@project = Project.new(project_params)
		
		if @project.save
			render json: {id: @project.id, status: :created}
		else
			render json: {errors: @project.errors, status: :unprocessable_entity}
		end
	end



	
	def update
		id = project_params[:id]
		@project = Project.find_by_id id

		project_to_update = project_params

		project_items = project_to_update.delete("project_items").values #pulls out of array

		project_items.each do |pi|
			id = pi[:id]

			unless(id.nil?)
				project_item = ProjectItem.find_by_id id
				project_item.update(pi)
			else
				project_item = ProjectItem.new(pi);
				project_item.save
			end
		end 


		project_to_update[:project_type] = project_params[:project_type].to_i

		if @project.update(project_to_update) 
			render json: {status: 'updated', id: @project.id }
		else
			render json: @project.errors, status: :unprocessable_entity
		end
	end

	def delete
		
	end

#public methods
	def show
		
	end

	def index
		@project_groups = Project.order(:sort_order)
								 .group_by(&:project_type)
								 .map do |p_type, project|
									{p_type: p_type, projects: project}
								 end 
	end

	private
	def authenticate_admin
		#get cookie for admin

		#redirect to not_authorized page? Or Login?
	end

	def find_project
		id = params[:id]
		@project = Project.find_by_id id

		respond_to do |format|
			format.html {render('welcome/notfound')}
			format.json {render json: {error: "not-found"}.to_json, status: 404}
		end if @project.nil?
	end

	def project_params
		params.require(:project).permit(:id, :project_title, :sort_order, 
			:project_type, :project_markdown, 
			:project_items => [:id, :image_url, :image_name, 
				:image_caption,
				:is_thumb_image,
				:project_id])
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@project_groups = Project.order(:sort_order)
								 .group_by(&:project_type)
								 .map do |p_type, project|
									{p_type: p_type, projects: project}
								 end 
  end

  def about

  end

  def notfound

  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdownToHtml html
		renderer_options = {filter_html: true}
		renderer = Redcarpet::Render::HTML.new(renderer_options)
		markdowner = Redcarpet::Markdown.new(renderer)
		markdowner.render(html).html_safe
	end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/edit.html.erb
<script>
var gNs = gNs || {};
var projectId = <%= @id %>
$(document).on("page:load ready", gNs.init(projectId));
</script>
<div class="edit-form">
	<table>
		<tbody>
			<tr>
				<th>Project Name:</th>
				<td><input type="text" data-bind="value: $data.project.project_title, valueUpdate:'afterkeydown'" /></td>
			</tr>
			<tr>
				<th>Sort Order</th>
				<td><input type="number" data-bind="value: $data.project.sort_order, valueUpdate:'afterkeydown'" /></td>
			</tr>
			<tr>
				<th>Project Type</th>
				<td><select data-bind="options: $data.project.project_type_options, optionsText: 'type', optionsValue: 'value', value: $data.project.project_type" /></td>
			</tr>
			<tr>
				<th>Project Description (left column Html):</th>
				<td><textarea data-bind="value: $data.project.project_markdown, valueUpdate:'afterkeydown'"></textarea></td>
			</tr>
		</tbody>
	</table>
	<h1>Add/Edit Project Items</h1>
	<button type="button" data-bind="click: $data.project.addProjectItem">Add Item</button>
	<div class="project-item-section" data-bind="foreach: $data.project.project_items">
		<h3 data-bind="text: $data.projectItemDisplayName, click: $parent.project.setSelectedProjectItem"></h3>
	</div>
	<div data-bind="visible: $data.project.isSelected()">
		<h3>Edit Project Item</h3>
		<label>Image Name (what's displayed on hover)</label>
		<input  type="text" data-bind="value: $data.project.selectedProjectItem().image_name"/>
		<br/>
		<label>Image Caption (what's displayed underneath photo)</label>
		<input  type="text" data-bind="value: $data.project.selectedProjectItem().image_caption" />
		<br/>
		<label>Mark as Thumb Image</label>
		<input  type="checkbox" data-bind="checked: $data.project.selectedProjectItem().is_thumb_image"/>
		<br/>
		<label>Placeholder for File Upload?</label>
	</div>
	<button type="button" data-bind="click: $data.submitChanges">Save Changes</button>
	
</div>
<div class="project-preview">
	<div>
		<h1 data-bind="text: $data.project.project_title"></h1>
		<div class="left-column" data-bind="markdown: $data.project.project_markdown">
		</div>
		<div class="right-column">
			<div data-bind="foreach: $data.project.projectViewItems">
				<img data-bind="attr: {src: $data.image_url, alt: $data.image_name}" />
				<p class="caption" data-bind="visible: $data.image_caption !== ''">
				</p>
			</div>
			
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Alexandra Doffing Design</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,400' rel='stylesheet' type='text/css'>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon'%>
	</head>
	<% if controller.controller_name == 'admin' %>
	<body >
		<% else %>
		<body>
			<% end %>
			<div id="container">
				<div class="topnav-placeholder nav"></div>
				<div class="topnav nav">
					<div class="site-links-icon"></div>
					<div class="site-links">
						<ul>
							<li><a href=<%= root_url %>>home</a></li>
							<li><a href="/welcome/about" >about</a></li><!-- 
							<li><a href=<%= portfolio_root_url %>>portfolio</a></li> -->
							<!-- <li><a href=<%= shop_root_url %>>shop</a></li> -->
							<li><a href="/welcome/contact">contact</a></li>
						</ul>
					</div>
					
					</div><!-- end topnav -->
					<div class="logo-container nav">
						<a href=<%= root_url %> ><img src="/images/logo.png" alt="Doffing Design" /></a>
					</div>
					<div id="main">
						<%= yield %>
						
						</div><!-- end main -->
						<div class="footer">
							<div class="social">
								<a class="dribbble" href="https://dribbble.com/alexandradoffing" target="_blank"></a>
								<a class="twitter" href="https://twitter.com/doffingdesign" target="_blank"></a>
								<a class="instagram" href="http://instagram.com/doffingdesign" target="_blank"></a>
								<a class="linkedin" href="https://www.linkedin.com/pub/alexandra-doffing/20/2b3/624" target="_blank"></a>
								</div><!-- end social -->
								<p>&copy; 2015 Alexandra Doffing Design, LLC</p>
								<p>All Rights Reserved</p>
								</div><!-- end footer -->
								</div><!-- end container -->
								
							</body>
						</html>

app/views/project/index.html.erb
<div>
	<h1>Welcome to Alexandra Doffing Design!</h1>
	<p>
		Take a look around! This is a brand new site so there will be plenty of new content and features to come but in the meantime, check out 
		my projects below!  If you like what you see or you simply want to send me sweet words via email, you can get my contact information via the Contact page.
	</p>
	<div>
		<% @project_groups.each do |g|%>
		<div class="cf">
			<h3> <%= g[:p_type] %></h3>
			<% g[:projects].each_with_index do |proj, i| %>
			<% col_idx = "col-" + ((i % 3) + 1).to_s %>
			<div class="<%= col_idx %> project">
				<% unless @isAdmin.nil? %>
				<a class="edit-tag" href="/admin/edit/<%= proj.id %>"></a>
				<% end %>
				<a href="<%= project_url(proj.id) %>"><img src="<%= proj.thumbnail_image %>" /></a>
				<a href="<%= project_url(proj.id)  %>"><%= proj.project_title %></a>
			</div>
			<% end %>
		</div>
		<% end %>
		<% unless @isAdmin.nil? %>
		<p>
			Dis is an admin block. This should show at admin/index
		</p>
		<% end %>
	</div>
</div>

app/views/project/show.html.erb
<div>
	<h1><%= @project.project_title %></h1>

			<div class="left-column">
				<%= markdownToHtml(@project.project_markdown) %>
				
			</div>

			<div class="right-column column">
				
				<% @project.project_view_items.each do |p|  %>
				<img src="<%= p.image_url %>" />

					<% unless p.image_caption.nil? %>
						<p class="caption">  
							<%= p.image_caption  %>
						</p>

					<% end %>

				<% end %>
			</div>
</div>

app/views/welcome/about.html.erb

<div class="left-column column">
	<img src="../images/about-alex.png" alt="Alex Doffing" />
</div>
<div class="right-column">
	<h1>About Alexandra Doffing</h1>
	<h2>Hello!</h2>
	<p>I am a Minnesota artist, based in Minneapolis. I attended Drake University and received degrees for Graphic Design and Creative Advertising in the spring of 2010.</p>
	<p>As you will see, my work is composed of primarily graphite drawings and flat, vector illustrations. I am expanding into pattern making, which seems to be my happy place. This site was a foray into web design, which is another area in which I am gaining ground.</p>
	<p> I am very open to any freelance opportunities, be they for illustration, design, or other creative project. Please <a href="mailto:doffingdesign@gmail.com">inquire</a> to start a conversation regarding any custom design work.</p>
	<p><i>Member of <a href="http://www.aiga.org/" target="_blank">AIGA</a> since 2009.</i>
	<h2>Client Testimonials</h2>
	<p>"Alexandra has been an absolute joy to work with. Her creativity is brilliant. We're extremely pleased with the beautiful work she's done for us."<br />
	<i>Stephanie Flies, Owner of City Moms Blog Network</i></p>
	<p>"We highly recommend using Alex for your designing needs. We came to her to help design our "Save the Date" card that uniquely captured our love for all things Minneapolis. They turned out so perfectly that we asked her to also design our program and table tents&mdash;which she delivered upon above and beyond what we ever imagined. She really "got" our style and we received tons of compliments on our wedding day. Alex is very talented, creative, thoughtful and goes above and beyond to satisfy her clients. Oh, and if that isn't enough&mdash;she works incredibly fast. It was such a pleasure working with her and we recommend Alex to anyone looking for a fresh and fun design concept! Thanks, Alex!"<br />
	<i>Lori &amp; Erin Bodner</i></p>
</div>

app/views/welcome/contact.html.erb
<div>
	<h1>Contact</h1>
	<p>Email is the best way to contact me directly: <a href="mailto:doffingdesign@gmail.com">doffingdesign@gmail.com</a></p>
	<p>The portfolio on this site is not the only place to see my work. I belong to these networks (and update them with varying levels of regularity) as well:</p>
	<ul>
		<li><a href="https://www.behance.net/AlexandraDoffing" target="_blank">Behance</a></li>
		<li><a href="https://dribbble.com/alexandradoffing" target="_blank">Dribbble</a></li>
		<li><a href="https://twitter.com/doffingdesign" target="_blank">Twitter</a></li>
		<li><a href="https://doffingdesign.wordpress.com/" target="_blank">Wordpress</a></li>
		<li><a href="https://instagram.com/doffingdesign/" target="_blank">Instagram</a></li>
		<li><a href="https://www.linkedin.com/pub/alexandra-doffing/20/2b3/624" target="_blank">Linkedin</a></li>
	</ul>
	<p>Or you can buy my wares any of these kind places:</p>
	<ul>
		<li><a href="http://society6.com/doffingdesign" target="_blank">Society6</a></li>
		<li><a href="http://www.spoonflower.com/profiles/doffingdesign" target="_blank">Spoonflower</a></li>
		<li><a href="http://www.muralsyourway.com/alexandra-doffing-prints/" target="_blank">Murals Your Way</a></li>
		<li><a href="https://www.etsy.com/shop/DoffingDesign?ref=hdr_shop_menu" target="_blank">Etsy</a></li>
	</ul>
</div>

app/views/welcome/index.html.erb
<div>
			<h1>h1 header line</h1>

			<p>Candy canes gummies sugar plum oat cake oat cake dragée carrot cake sesame snaps. Jujubes gingerbread sesame snaps bear claw candy canes gingerbread donut. Caramels halvah apple pie pudding.</p>

			<p>Biscuit liquorice soufflé macaroon jujubes lemon drops. Macaroon brownie jelly-o cheesecake candy lollipop biscuit jujubes. Lollipop halvah tootsie roll caramels ice cream ice cream. Gummies ice cream liquorice cheesecake candy canes.</p>

			<h2>h2 header line</h2>

			<p>Liquorice candy canes chupa chups topping fruitcake cheesecake icing pastry unerdwear.com. Danish marshmallow donut apple pie. Cake cotton candy caramels donut applicake.</p>

			<h3>h3 header line</h3>

			<p>Toffee ice cream donut jelly beans. Marzipan soufflé halvah. Dessert gummi bears cookie.</p>

			<h3>h3 header line</h3>

			<p>Marshmallow candy unerdwear.com cookie jelly candy canes candy canes sweet. Cheesecake unerdwear.com sweet bear claw biscuit cupcake. Sweet bonbon wafer sugar plum powder. Jelly-o powder tiramisu dessert lollipop jelly beans.</p>


</div>

app/views/welcome/notfound.html.erb
<div>
<h1>Not Found</h1>
</div>